name: cover-parse-batch

on:
  workflow_dispatch:
    inputs:
      jobName:
        description: 'Job Name'
        required: true
        type: string
      jobType:
        description: 'Cover Parse Job Type'
        required: true
        default: 'listopia_parser'
        type: choice
        options:
          - hot_cover_parser
          - listopia_parser
      listopiaUrl:
        description: 'Listopia URL For Scraping'
        required: false
        default: 'https://www.goodreads.com/list/show/4581.Judge_A_Book_By_Its_Cover_'
        type: string
      pageStart:
        description: 'The page number for Listopia parser to start on'
        required: false
        default: 1
        type: number
      pageCount:
        description: 'Number of Listopia pages to Scrape'
        required: false
        default: 10
        type: number
      maxParallelCount:
        description: 'Maximum number of scraping calls to run in parallel'
        required: false
        default: 4
        type: number
      popularCount:
        description: 'Maximum number of popular books to pull'
        required: false
        default: 25
        type: number
      trendingCount:
        description: 'Maximum number of trending books to pull'
        required: false
        default: 25
        type: number

permissions:
  id-token: write
  contents: read

jobs:
  submit-batch:
    name: Submit Batch Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure AWS Credentials for github actions
        uses: aws-actions/configure-aws-credentials@v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Submit Listopia Parser Job
        if: ${{ inputs.jobType == 'listopia_parser' }}
        run: |
          aws batch submit-job \
              --job-name ${{ inputs.jobName }}-${{ github.run_id }} \
              --job-queue listopia-queue \
              --job-definition listopia_parser_batch_job_definition \
              --container-overrides '{
                "environment": [
                  {
                    "name": "JOB_TYPE",
                    "value": "${{ inputs.jobType }}"
                  },
                  {
                    "name": "ListopiaOptions__ListopiaUrl",
                    "value": "${{ inputs.listopiaUrl }}"
                  },
                  {
                    "name": "ListopiaOptions__PageStart",
                    "value": "${{ inputs.pageStart }}"
                  },
                  {
                    "name": "ListopiaOptions__PageCount",
                    "value": "${{ inputs.pageCount }}"
                  },
                  {
                    "name": "ListopiaOptions__MaxParallelCount",
                    "value": "${{ inputs.maxParallelCount }}"
                  }
                ]
              }'
          
      - name: Submit Hot Cover Parser Job
        if: ${{ inputs.jobType == 'hot_cover_parser' }}
        run: |
          aws batch submit-job \
              --job-name ${{ inputs.jobName }}-${{ github.run_id }} \
              --job-queue listopia-queue \
              --job-definition listopia_parser_batch_job_definition \
              --container-overrides '{
                "environment": [
                  {
                    "name": "JOB_TYPE",
                    "value": "${{ inputs.jobType }}"
                  },
                  {
                    "name": "HotCoverOptions__PopularCount",
                    "value": "${{ inputs.popularCount }}"
                  },
                  {
                    "name": "HotCoverOptions__TrendingCount",
                    "value": "${{ inputs.trendingCount }}"
                  }
                ]
              }'
